import fs from 'fs';

function base64_encode(file) {
  return fs.readFileSync(__dirname + `/member/${file}`, {encoding: 'base64'});
}
const memberArr = [
  'DiZhang.jpg',
  'guyoung.jpg',
  'jh.jpg',
  'hj.JPG',
  'hyunkyu.png',
  'junhan.jpg',
  'junwon.jpg',
  'kwangjin.png',
  'Luong.jpg',
  'Sangtae.png',
  'seunghwan.jpg',
  'seungnyun.jpg',
  'TangJianhua.JPG',
  'wonjun.jpg',
  'yongjun.jpg',
];
let image = {};
memberArr.map((a) => {
  image[`${a}`] = base64_encode(`${a}`);
});

const person = [
  {
    graduated: false,
    name: 'Jianhua Tang',
    field: 'Cloud radio access network',
    email: 'jianhua_tang@islab.snu.ac.kr',
    title: 'PhD',
    year: '',
    occupation: '',
    image: image['TangJianhua.JPG'],
    imageName: 'TangJianhua.JPG',
    profilePage: 'https://sites.google.com/site/ericjianhuatang/'
  },
  {
    graduated: false,
    name: 'Di Zhang',
    field: 'B5G and 6G communications',
    email: 'di_zhang@islab.snu.ac.kr',
    title: 'PhD',
    year: '',
    occupation: '',
    image: image['DiZhang.jpg'],
    imageName: 'DiZhang.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Luong Trung Nguyen',
    field: 'Convex optimization for signal processing',
    email: 'ltnguyen@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['Luong.jpg'],
    imageName: 'Luong.jpg',
    profilePage: '',
    address: '1117 Bldg. 301, SNU'
  },
  {
    graduated: false,
    name: 'Sangtae Kim',
    field: 'Machine learning for bigdata systems',
    email: 'stkim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['Sangtae.png'],
    imageName: 'Sangtae.png',
    profilePage: '',
    address: '1117 Bldg. 301, SNU'
  },
  {
    graduated: false,
    name: 'Hyoungju Ji',
    field: 'B5G and 6G communications',
    email: 'hyoungjuji@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['hj.JPG'],
    imageName: 'hj.JPG',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Jinhong Kim',
    field: 'Compressed sensing and sparse signal recovery',
    email: 'jhkim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['jh.jpg'],
    imageName: 'jh.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Wonjun Kim',
    field: 'B5G and 6G communications',
    email: 'wjkim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['wonjun.jpg'],
    imageName: 'wonjun.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Guyoung Lim',
    field: 'B5G and 6G communications',
    email: 'gylim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['guyoung.jpg'],
    imageName: 'guyoung.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Seungnyun Kim',
    field: 'B5G and 6G communications',
    email: 'snkim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['seungnyun.jpg'],
    imageName: 'seungnyun.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Junhan Kim',
    field: 'Compressed sensing and sparse signal recovery',
    email: 'junhankim@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['junhan.jpg'],
    imageName: 'junhan.jpg',
    profilePage: '',
    address: '1117 Bldg. 301, SNU'
  },
  {
    graduated: false,
    name: 'Seunghwan Lee',
    field: 'Machine learning for wireless systems',
    email: 'shlee@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['seunghwan.jpg'],
    imageName: 'seunghwan.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Hyunkyu Joo',
    field: 'Machine learning for wireless systems',
    email: 'hkjoo@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['hyunkyu.png'],
    imageName: 'hyunkyu.png',
    profilePage: '',
    address: '1117 Bldg. 301, SNU'
  },
  {
    graduated: false,
    name: 'Kwangjin Lee',
    field: 'Machine learning for wireless systems',
    email: 'kjlee@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['kwangjin.png'],
    imageName: 'kwangjin.png',
    profilePage: '',
    address: '1117 Bldg. 301, SNU'
  },
  {
    graduated: false,
    name: 'Yongjun Ahn',
    field: 'B5G and 6G communications',
    email: 'yjahn@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['yongjun.jpg'],
    imageName: 'yongjun.jpg',
    profilePage: ''
  },
  {
    graduated: false,
    name: 'Junwon Son',
    field: 'B5G and 6G communications',
    email: 'jwson@islab.snu.ac.kr',
    title: '',
    year: '',
    occupation: '',
    image: image['junwon.jpg'],
    imageName: 'junwon.jpg',
    profilePage: ''
  },

  {
    graduated: true,
    name: 'Heejin Seo',
    field: '',
    email: '',
    title: 'Master',
    year: '2017',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Yunquan Dong',
    field: '',
    email: '',
    title: 'Postdoc',
    year: '2016',
    occupation: 'Professor in NUIST, China',
    image: '',
    profilePage: 'http://dxy.nuist.edu.cn/Teacher.aspx?T=002785',
  },
  {
    graduated: true,
    name: 'Sunho Park',
    field: '',
    email: '',
    title: 'PhD',
    year: '2015',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Sungpil Shin',
    field: '',
    email: '',
    title: 'Master',
    year: '2015',
    occupation: 'ETRI',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Jaeseok Lee',
    field: '',
    email: '',
    title: 'PhD',
    year: '2015',
    occupation: 'Hanwha Systems',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Chai Lim',
    field: '',
    email: '',
    title: 'PhD',
    year: '2015',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Suhyuk Kwon',
    field: '',
    email: '',
    title: 'PhD',
    year: '2014',
    occupation: 'Samsung Display',
    image: '',
    profilePage: 'http://islab.snu.ac.kr/shkwon/',
  },
  {
    graduated: true,
    name: 'Byungju Lee',
    field: '',
    email: '',
    title: 'PhD',
    year: '2014',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Jian Wang',
    field: '',
    email: '',
    title: 'PhD',
    year: '2013',
    occupation: 'Professor in Fudan University, China',
    image: '',
    profilePage: 'https://sites.google.com/site/jianwanghomepage/',
  },
  {
    graduated: true,
    name: 'Hyunjo Chung',
    field: '',
    email: '',
    title: 'PhD',
    year: '2013',
    occupation: 'CTO, Aradnetworks',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Wonkyu Seok',
    field: '',
    email: '',
    title: 'Master',
    year: '2013',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Chaehee Lim',
    field: '',
    email: '',
    title: 'Master',
    year: '2013',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Hyoungyoul Yu',
    field: '',
    email: '',
    title: 'PhD',
    year: '2012',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Miri Ha',
    field: '',
    email: '',
    title: 'Master',
    year: '2011',
    occupation: 'Korean Air',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Hyuk Lee',
    field: '',
    email: '',
    title: 'Master',
    year: '2011',
    occupation: 'Samsung Electronics',
    image: '',
    profilePage: '',
  },
  {
    graduated: true,
    name: 'Jungyong Park',
    field: '',
    email: '',
    title: 'Master',
    year: '2010',
    occupation: 'LG Electronics',
    image: '',
    profilePage: '',
  },
];

export default person;